apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: my-app
  template:
    metadata:
      labels:
        app: my-app
    spec:
      containers:
      - name: my-container
        image: nginx:latest
        volumeMounts:
        - name: custom-file-volume
          mountPath: /etc/custom
      volumes:
      - name: custom-file-volume
        configMap:
          name: custom-configmap